### ISSUE TITLE
Clicking on an empty space redirects to the Telegram page

### ISSUE THREAD

**Issue by nakazanie-ton** [TON-Market-Cap/bugs#1]
### Record
https://user-images.githubusercontent.com/16106529/199259718-bf38b4be-c3df-49a1-be1a-a43aefb3aaa9.mp4

### Issue
Clicking on an empty space redirects to the Telegram page

### Should be
No actions

**Comment by danya7423** [comment]
The ad box is the full width of the page. This is how it should be.
