### ISSUE TITLE
Clicking in the top markets section results in an unexpected error

### ISSUE THREAD

**Issue by nakazanie-ton** [TON-Market-Cap/bugs#2]
### Record

https://user-images.githubusercontent.com/16106529/199261278-f9d12264-0501-4fe0-87a8-b044d5144bf6.mov

### Issue
When you click on the TonRocket or TonSwap, or JettonEx section, an unexpected error message appears

### Should be
Page with selected market statistics appeared

**Comment by danya7423** [comment]
fixed
