### ISSUE TITLE
The converter line with the TON currency is disabled

### ISSUE THREAD

**Issue by nakazanie-ton** [TON-Market-Cap/bugs#3]
### Screenshot
<img src="https://user-images.githubusercontent.com/16106529/199262551-d5be686d-3b79-48a7-b41f-dd30df8ef869.png" width="250" height="400"> </img>

### Issue
The ton row is disabled. Cant tap on switch button while using converter.

**Comment by danya7423** [comment]
That's the way it's meant to be. There is no TON -> Jetton converter yet.

**Comment by nakazanie-ton** [comment]
@danya7423  Also converter types are not decimals

<img src="https://user-images.githubusercontent.com/16106529/199268127-72010dd6-bdd4-4b72-9333-ecf6ca37f460.png" width="250" height="400"> </img>

<img src="https://user-images.githubusercontent.com/16106529/199268211-13d54699-2e28-48ef-90ff-a183d7256c30.png" width="250" height="400"> </img>
