### ISSUE TITLE
Clicking my wallet at the top right corner results an unexpected exception

### ISSUE THREAD

**Issue by nakazanie-ton** [TON-Market-Cap/bugs#4]
### Record

https://user-images.githubusercontent.com/16106529/199263785-9e941a11-39bc-45a4-b120-807f5097501a.mov

### Issue
My wallet drop down menu is not working

**Comment by danya7423** [comment]
Can you share your wallet address? We need it to check this bug and send the reward when the contest is over.

**Comment by nakazanie-ton** [comment]
@danya7423 EQCJ81a9ELPIYJGHxavNe7HVhAx_iojnPev_jmT_2PEgEAic

**Comment by danya7423** [comment]
Hi. Thank you for your great work! We will send the award out within a few days
