### ISSUE TITLE
Clicking on the shift icon in the converter

### ISSUE THREAD

**Issue by l8goo** [TON-Market-Cap/bugs#5]
https://user-images.githubusercontent.com/113780853/199288219-84d9f316-f09f-40f7-b14e-d6cff8f9dae8.MP4

![image_2022-11-01_19-38-18](https://user-images.githubusercontent.com/113780853/199288222-37ceb346-477e-4f24-95ec-0b7dd103e109.png)

**Issue**
Nothing happens when I try to change tokens in the converter

**Should be**
Convertible Coins Must Change

**Comment by danya7423** [comment]
At the moment, this feature is not available and we do not plan to add it in the near future.
