### ISSUE TITLE
Wrong jetton data

### ISSUE THREAD

**Issue by nakazanie-ton** [TON-Market-Cap/bugs#6]
### Screenshot
![FC132B8F-A80B-44F3-9E55-E0F6BF0A56CE](https://user-images.githubusercontent.com/16106529/199343091-ce9b39c4-8157-4760-936a-f71941f789b8.png)

### issue

Wrong jetton data on main page. There is two bolt tokens.

**Comment by ilyaqznetsow** [comment]
![13814871-D234-48E6-AFFD-23D3EB8891A4](https://user-images.githubusercontent.com/16106529/199343653-7155f322-172d-4e9a-a936-b8eac90303a8.png)
![4EC8D741-3B8E-4FEA-A686-427B7079DD5D](https://user-images.githubusercontent.com/16106529/199343670-fbb8b2e9-3105-41ab-a9c8-46a961f9bb79.png)

**Comment by nakazanie-ton** [comment]
![C273BE67-A9A1-46B4-826A-C803B490AB6D](https://user-images.githubusercontent.com/16106529/199343842-b231ea03-dd17-45a9-a2c5-9691116d4e0a.png)
![B92B7C5A-93C3-4904-AEE4-B6A5D5997964](https://user-images.githubusercontent.com/16106529/199343849-9497fed1-0f08-45c6-9299-10e3ce180269.png)

Market section also in trouble

**Comment by danya7423** [comment]
So, tonight we had a large number of unknown bugs and artifacts. Everything is already functioning normally.
