### ISSUE TITLE
Wrong value in fiat currency

### ISSUE THREAD

**Issue by l8goo** [TON-Market-Cap/bugs#9]
**Screenshot**

![image_2022-11-02_19-39-58](https://user-images.githubusercontent.com/113780853/199550975-02c99732-c974-4840-89c0-a803cfd25373.png)
![image_2022-11-02_19-40-22](https://user-images.githubusercontent.com/113780853/199550982-1bdb0161-6a95-4ed6-9886-53fed72f6e58.png)
![image_2022-11-02_19-40-57](https://user-images.githubusercontent.com/113780853/199550987-0d475f80-b4b3-4d11-a316-46a2cf1b0313.png)

**Issue**
Incorrect conversion of tokens to fiat currencies.

**Comment by danya7423** [comment]
Hi, can you share your wallet address? We want to send you a reward for found bugs :)
